
spring:
  application:
    name: feignclient-url-not-refresh-eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: htttp://localhost:${server.port}/eureka
server:
  port: 8761